# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransferOutMismatch.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TransferOutMismatch.proto',
  package='',
  serialized_pb='\n\x19TransferOutMismatch.proto\"\xd8\x01\n\x13transferOutMismatch\x12\x15\n\rtransactionId\x18\x01 \x02(\t\x12\x17\n\x0ftransactionType\x18\x02 \x02(\t\x12\x11\n\trequestNo\x18\x03 \x02(\t\x12\x0f\n\x07\x63ompany\x18\x04 \x02(\t\x12\x19\n\x11\x64\x61taErrorDateTime\x18\x05 \x02(\t\x12\x10\n\x08\x63reateBy\x18\x06 \x02(\t\x12\x16\n\x0e\x63reateDateTime\x18\x07 \x02(\t\x12\x10\n\x08updateBy\x18\x08 \x02(\t\x12\x16\n\x0eupdateDateTime\x18\t \x02(\t')




_TRANSFEROUTMISMATCH = _descriptor.Descriptor(
  name='transferOutMismatch',
  full_name='transferOutMismatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transactionId', full_name='transferOutMismatch.transactionId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transactionType', full_name='transferOutMismatch.transactionType', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requestNo', full_name='transferOutMismatch.requestNo', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='company', full_name='transferOutMismatch.company', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataErrorDateTime', full_name='transferOutMismatch.dataErrorDateTime', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='createBy', full_name='transferOutMismatch.createBy', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='createDateTime', full_name='transferOutMismatch.createDateTime', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='updateBy', full_name='transferOutMismatch.updateBy', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='updateDateTime', full_name='transferOutMismatch.updateDateTime', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=246,
)

DESCRIPTOR.message_types_by_name['transferOutMismatch'] = _TRANSFEROUTMISMATCH

class transferOutMismatch(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRANSFEROUTMISMATCH

  # @@protoc_insertion_point(class_scope:transferOutMismatch)


# @@protoc_insertion_point(module_scope)
